-- Inserção de dados na tabela FUNCIONARIOS
INSERT INTO USR_GESTAO_PROJ.FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (1, 'João Silva', TO_DATE('1985-03-15', 'YYYY-MM-DD'), 'Gerente de Projetos', 5000.00, TO_DATE('2015-01-01', 'YYYY-MM-DD'));

INSERT INTO USR_GESTAO_PROJ.FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (2, 'Maria Oliveira', TO_DATE('1990-07-22', 'YYYY-MM-DD'), 'Analista de Sistemas', 3500.00, TO_DATE('2018-05-20', 'YYYY-MM-DD'));

-- Inserção de dados na tabela PROJETOS
INSERT INTO USR_GESTAO_PROJ.PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (1, 'Projeto Alpha', 'Desenvolvimento de um novo sistema de gestão', TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2023-12-31', 'YYYY-MM-DD'), 100000.00);

-- Inserção de dados na tabela TAREFAS
INSERT INTO USR_GESTAP_PROJ.TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (1, 1, 'Análise de Requisitos', 'Coleta de requisitos do cliente', 2, TO_DATE('2023-02-01', 'YYYY-MM-DD'), TO_DATE('2023-02-28', 'YYYY-MM-DD'), 'Concluída');

-- Inserção de dados na tabela ALOCACOES_RECURSOS
INSERT INTO USR_GESTAO_PROJ.ALOCACOES_RECURSOS (ALOCACAO_ID, PROJETO_ID, FUNCIONARIO_ID, HORAS_TRABALHADAS)
VALUES (1, 1, 1, 160.00);

INSERT INTO USR_GESTAO_PROJ.ALOCACOES_RECURSOS (ALOCACAO_ID, PROJETO_ID, FUNCIONARIO_ID, HORAS_TRABALHADAS)
VALUES (2, 1, 2, 120.00);
